export function byId(id, root = document) {
  return root.getElementById(id);
}

export function cacheElements(root = document) {
  return {
    catalogMeta: byId('catalog-meta', root),
    archiveNote: byId('archive-note', root),
    tabs: [...root.querySelectorAll('.tab')],
    archivePanel: byId('archive-panel', root),
    mapPanel: byId('map-panel', root),
    livePanel: byId('live-panel', root),
    spectrogramPanel: byId('spectrogram-panel', root),
    sanctuary: byId('s-sanctuary', root),
    category: byId('s-cat', root),
    label: byId('s-label', root),
    description: byId('s-desc', root),
    date: byId('s-date', root),
    site: byId('s-site', root),
    file: byId('s-file', root),
    waveform: byId('waveform', root),
    prevButton: byId('btn-prev', root),
    playButton: byId('btn-play', root),
    playIcon: byId('play-icon', root),
    nextButton: byId('btn-next', root),
    shuffleButton: byId('btn-shuffle', root),
    detailsButton: byId('btn-details', root),
    progress: byId('progress', root),
    status: byId('status', root),
    time: byId('time', root),
    detailPanel: byId('track-detail', root),
    detailTitle: byId('detail-title', root),
    detailCloseButton: byId('btn-detail-close', root),
    detailSanctuary: byId('detail-sanctuary', root),
    detailCategory: byId('detail-category', root),
    detailRecorded: byId('detail-recorded', root),
    detailSite: byId('detail-site', root),
    detailDeployment: byId('detail-deployment', root),
    detailDuration: byId('detail-duration', root),
    detailProfile: byId('detail-profile', root),
    detailFilename: byId('detail-filename', root),
    detailDescription: byId('detail-description', root),
    detailVariants: byId('detail-variants', root),
    detailSourceLink: byId('detail-source-link', root),
    copySourceButton: byId('btn-copy-source', root),
    query: byId('search-input', root),
    sanctuarySelect: byId('sanctuary-filter', root),
    sortSelect: byId('sort-select', root),
    categoryBar: byId('cat-bar', root),
    resultCount: byId('result-count', root),
    trackList: byId('tlist', root),
    emptyState: byId('empty-state', root),
    mapCategoryFilter: byId('map-category-filter', root),
    mapYearFilter: byId('map-year-filter', root),
    leafletMap: byId('leaflet-map', root),
    mapSummary: byId('map-summary', root),
    liveGrid: byId('live-grid', root),
    spectrogramEmpty: byId('spectrogram-empty', root),
    spectrogramImg: byId('spectrogram-img', root),
    audio: byId('audio', root),
  };
}
