window.OCEAN_JUKEBOX_SANCTUARIES = [
  {
    name: 'Hawaiian Islands',
    displayName: 'Hawaiian Islands Humpback Whale National Marine Sanctuary',
    coordinates: [20.7, -156.5],
    zoom: 6,
    region: 'Pacific Islands',
    note: 'Humpback whale breeding waters and broad tropical reef soundscapes.',
  },
  {
    name: 'Channel Islands',
    displayName: 'Channel Islands National Marine Sanctuary',
    coordinates: [34.0, -120.2],
    zoom: 7,
    region: 'West Coast',
    note: 'Kelp forests, islands, and productive waters off southern California.',
  },
  {
    name: 'Monterey Bay',
    displayName: 'Monterey Bay National Marine Sanctuary',
    coordinates: [36.8, -121.9],
    zoom: 7,
    region: 'West Coast',
    note: 'Deep submarine canyon habitat with fish calls and passing marine mammals.',
  },
  {
    name: 'Olympic Coast',
    displayName: 'Olympic Coast National Marine Sanctuary',
    coordinates: [47.7, -124.7],
    zoom: 7,
    region: 'Pacific Northwest',
    note: 'Cold, energetic waters along Washington coastal shelf and slope habitats.',
  },
  {
    name: "Gray's Reef",
    displayName: "Gray's Reef National Marine Sanctuary",
    coordinates: [31.4, -80.9],
    zoom: 8,
    region: 'Southeast',
    note: 'Live-bottom reef habitat off Georgia with fish and storm recordings.',
  },
  {
    name: 'Stellwagen Bank',
    displayName: 'Stellwagen Bank National Marine Sanctuary',
    coordinates: [42.4, -70.3],
    zoom: 8,
    region: 'Northeast',
    note: 'Productive bank east of Boston known for cod, whales, and vessel traffic.',
  },
  {
    name: 'Papahānaumokuākea',
    displayName: 'Papahanaumokuakea Marine National Monument',
    coordinates: [25.7, -171.7],
    zoom: 5,
    region: 'Pacific Islands',
    note: 'Remote Northwestern Hawaiian Islands monument with coral reef soundscapes.',
  },
  {
    name: 'Florida Keys',
    displayName: 'Florida Keys National Marine Sanctuary',
    coordinates: [24.6, -81.7],
    zoom: 7,
    region: 'Southeast',
    note: 'Coral reef soundscapes with grouper, midshipman, shrimp, and boat noise.',
  },
];
